### ISSUE TITLE
Animal MedPod(s) / VetPod(s)

### ISSUE THREAD

**Issue by sumghai** [sumghai/MedPod#11]
In a similar vein to the Animal Feeders from Replimat, it would be nice to have MedPod beds for pets and other colony animals.

Multiple variants may be required for animals of different sizes (especially mods that add dinosaurs and other megafauna). Alternatively, a large one-size-fits all bed could cover all the bases.

**Comment by dariumz** [comment]
Darium here. In my opinion, I would say do the sizing scheme that you prefer, generally speaking, I would go with the 1 size fits all. Whether or not people use other people's work shouldn't be your concern, after all, it's on voluntary basis people download your work, if they don't like it, they are free to either make their own or simply not use it.

Taking a look at vanilla Rimworld, that alone offers different sizes from rats to thrumbos, yet all animals can use the genetic animal cloth "bed".

**Comment by sumghai** [comment]
Fair point, @dariumz - I'll aim for a one-size-fits-all VetPod, with overall dimensions to fit the largest vanilla RimWorld animal (Thrumbo / Elephant).

**Comment by sumghai** [comment]
**In-game comparison of animal sizes**

![caribou](https://user-images.githubusercontent.com/4993380/102352309-a2b71b80-3fe2-11eb-9b51-c38a24275129.png)
![muffalo](https://user-images.githubusercontent.com/4993380/102352318-a5197580-3fe2-11eb-904e-ef63996953e0.png)
![thrumbo](https://user-images.githubusercontent.com/4993380/102352327-a6e33900-3fe2-11eb-9fe1-0125fc77dcf8.png)
![elephant](https://user-images.githubusercontent.com/4993380/102352333-a77bcf80-3fe2-11eb-87c8-5f30886b98ff.png)

**Comment by sumghai** [comment]
I've decided to instead create two different variants of the VetPod, with the idea being that players should have to choice of investing in either the smaller and cheaper version for ordinary household pets, or the larger and more expensive version for large farm animals and megafauna.

**VetPod**
* 3x3 cell footprint
* 2x2 cell bed size
* Supports pets and small domesticated animals with Body Size up to 0.875

**VetPod Mega (Planned)**
* 7x5 cell footprint
* 5x4 cell bed size
* Supports all pets and domesticated animals of any size

**Comment by sumghai** [comment]
This is good to go.

**Comment by sumghai** [comment]
Whoops, almost forgot to translate the new VetPods.

**Comment by sumghai** [comment]
There we go.
