### ISSUE TITLE
Incompatible with Rimworld of Magic

### ISSUE THREAD

**Issue by k4l1brx** [sumghai/MedPod#15]
My mages aren't getting healed in the medpod, and normal pawns are.

They are in the medpod for while, it says that the MedPod is finished healing but nothing changes.

**Comment by sumghai** [comment]
I'm not familiar with RoM, so you'll have to provide a bit more information:
- How do mages differ from regular pawns? Do they have a special hediff or something?
- Are MedPods having trouble treating a specific type of injury/hediff on mages? Or can they not even heal cuts and scratches on mages at all?

**Comment by k4l1brx** [comment]
> I'm not familiar with RoM, so you'll have to provide a bit more information:
> 
>     * How do mages differ from regular pawns? Do they have a special hediff or something?
> 
>     * Are MedPods having trouble treating a specific type of injury/hediff on mages? Or can they not even heal cuts and scratches on mages at all?

Yes, the mages do have special hediffs. 

![](https://i.imgur.com/SeGnf8n.png)

MedPods can't heal anything at all on mages, while they work with normal pawns with the same injuries.

**Comment by sumghai** [comment]
Thanks for getting back to me - I'll take a look when I have time.

**Comment by sumghai** [comment]
@k4l1brx - I examined your screenshot and the source code for RoM - Those whole-body hediffs are already marked as `<isBad>false</isBad>`, so they should already be safely ignored by the MedPod.

What I find particularly interesting, however, is that your mage pawn also has Torso implants like the Aesthetic shaper and Healing enhancer - I already have confirmed bug reports that Torso implants cause pawns to be trapped inside MedPods, which I have a working fix for in the pipeline.

Therefore, I suspect your problem might actually not be related to RoM.

Could you try reproducing your problem with a mage that **_does not_** have Torso implants of any kind?

**Comment by k4l1brx** [comment]
@sumghai  

So I was wrong. It works with pawn without Torso Implant.

Sorry for bothering you with this.

**Comment by sumghai** [comment]
No worries - thanks for clarifying!
