### ISSUE TITLE
Incompatible with Elite Bionics Framework

### ISSUE THREAD

**Issue by LastXsile** [sumghai/MedPod#16]
After breaking down my mod list I've determined what was causing the infinite loop of colonists with bionics to remain inside the medpod and not leaving until they healed naturally. Something in this mods framework is causing the issue. After removing it my mod list pawns are now correctly healing with damaged bionics. I would simply not use the mod if removing it on a current play through didn't cause issues. Hopefully it can be patched though if it needs to be fixed on the other mod authors side I will inquire to them about it if its not fixable on this side.

**Comment by sumghai** [comment]
Thanks for narrowing the issue down for me - I'll take a look when I have the time.

**Comment by sumghai** [comment]
@LastXsile - Do the colonists stuck inside the MedPod have _implants_ that specifically affect the Torso?

**Comment by LastXsile** [comment]
@sumghai Most of my colonists do, infact after removing elite bionics framework it destroyed those implants so this could have been the issue from the beginning. I would have to run some testing to be sure though.

**Comment by LastXsile** [comment]
@sumghai I've confirmed its just an issue with torso implants and the Elite Bionic Framework is compatible with the medpod. Upon leaving the framework installed and removing all implants that effect torso's everything works smoothly and with your lastest version the fps issue also has been solved.
