### ISSUE TITLE
Problem with 'puppets' from Android tiers.

### ISSUE THREAD

**Issue by CodePanter** [sumghai/MedPod#18]
From my testing, installing a 'VX0 neural chip' in a human colonist with other health problems (mine was missing an arm) will result in them being put in the medpod as expected. 

My colonist (in this case a prisoner that got converted with the chip) was put into a medpod to recover from some scarring and the missing arm. The colonist was still sedated from having the chip implanted, so when they were put in, their health tab showed a scar, a missing arm, the medpod coma, the sedation and the neural chip. 

It took a while for the missing arm to regenerate, but when that was done, the colonist was fully healed, got up out of the medpod with only the neural chip and 'cortical stimulation' showing in the health tab, walked a few steps and collapsed. The thing is, the walking is the problem. 

The cortical stimulation put consciousness to 100%, where the neural chip makes the colonist fully brain-dead. Before the cortical stimulation could even wear off, the colonist seemed to realized and dropped down. When the stimulation actually faded a few seconds later, nothing changed. 

Is this cortical stimulation supposed to give a colonist consciousness even in situations like these, or could you add a check that seems if anything else is making it impossible?

**Comment by sumghai** [comment]
The cortical stimulation is meant to wake the patient by cancelling the effects of the delta-wave induced coma applied during treatment.

I honestly don't know how I'm going to handle an outright bizarre edge case like this.

**Comment by CodePanter** [comment]
This causes no real problems for me as I can work around it quite easily but I thought you might want to know that in some cases, the cortical stimulation seems to do more than just undo the effects of the coma, and actually 'boost' the colonist beyond their natural state for a few seconds.
