### ISSUE TITLE
EPOE imcompability: AI Persona Core Implant

### ISSUE THREAD

**Issue by MerGatto** [sumghai/MedPod#20]
The AI Persona core Implant from EPOE causes an infinite Diagnosis Loop.
The Hediff from this implant requires periodical tending but the MedPod is not tending it because it's not marked with 'IsBad'.

This behavior is probably an issue for other mods as well.

Possible solution would be to also include Hediffs in the treatment list that require tending AND are not marked as 'IsBad'
and instead of removing the Hediff when healing  treat it with 100% instead

**Comment by sumghai** [comment]
Fixed in #21.
