### ISSUE TITLE
"Reatomizing" gets stuck at 88% on some pawns

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [sumghai/MedPod#39]
I *think* this may be related to Rimatomics radiation-exposure, although I haven't seen enough cases with devmode turned on to be sure it's what was causing it on past instances. Oddly, it *always* shows exactly 88% when a pawn is stuck on the bed.

<img width="618" alt="Screen Shot 2020-10-17 at 11 59 59" src="https://user-images.githubusercontent.com/200/96348705-5302b500-1070-11eb-8c5d-d2c1911a3d09.png">
<img width="872" alt="Screen Shot 2020-10-17 at 11 59 42" src="https://user-images.githubusercontent.com/200/96348707-55fda580-1070-11eb-8699-9889a80aef24.png">

Hugslib devlog: https://gist.github.com/ELLIOTTCABLE/b85587269bf22007aa378557a41c8999

**Comment by sumghai** [comment]
Have you tried this on a pawn with _only_ Radiation buildup from Rimatomics?

Also, I'm not familiar with the Synthetic heart hediff/implant. Where is that from?

**Comment by ELLIOTTCABLE** [comment]
Synthetic hediff is from Extended Prosthetic and Organ Engineering; and if it occurs again on a more-baseline pawn I'll definitely report back with more details! Unfortunately, I cannot reliably reproduce; it happens fairly randomly, as far as I can tell. /=

https://github.com/Aurani/EPOE-Forked/blob/8f6f4f9691a898aa70febc3ea3d35066832340b7/1.0/Defs/HediffDefs/HediffDefs_Synthetics.xml#L122-L131

**Comment by sumghai** [comment]
As the reporting user has not been able to reliably reproduce this issue, there's not much I can do.

Closing for now, unless the user has new information to offer.
