### ISSUE TITLE
When I have a colonists health tab open, sometimes the UI glitches when they finish their medpod treatment.

### ISSUE THREAD

**Issue by blkarcher77** [sumghai/MedPod#46]
**Describe the bug:**  
As the title states, sometimes when I have the health tab open to watch the medpod work, once the treatment is done, the UI glitches, looking like [this](https://i.imgur.com/7SF5k2f.jpg). As you can see, the health tab stays open, but is blank, the bottom bar disappears, and most of my colonists at the top disappear as well. The box in the middle is me saving the game, because when you save the game, and then reload it, the problem is solved. 

I don't know what the conditions need to be to recreate this glitch, as it doesn't happen every time.

**Expected behavior:**  

The entire UI gets glitched, so not that.

**Steps to reproduce:**  

I have no idea, because it doesn't happen every time. It rarely happens.

**Additional information:**

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit) 
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.2.2753
**RimWorld DLCs loaded:** None
**MedPod mod version:** 1.2.4
**MedPod mod downloaded from:** Steam 
**Your mod list:** 
Harmony | http://steamcommunity.com/sharedfiles/filedetails/?id=2009463077
HugsLib | http://steamcommunity.com/sharedfiles/filedetails/?id=818773962
Giddy-up! Core | http://steamcommunity.com/sharedfiles/filedetails/?id=1216999901
Camera+ | http://steamcommunity.com/sharedfiles/filedetails/?id=867467808
Allow Tool | http://steamcommunity.com/sharedfiles/filedetails/?id=761421485
Mad Skills | http://steamcommunity.com/sharedfiles/filedetails/?id=731111514
Jobs of Opportunity (While You're Up) | http://steamcommunity.com/sharedfiles/filedetails/?id=2034960453
Animals Logic | http://steamcommunity.com/sharedfiles/filedetails/?id=1098354593
[1.2] Removable Mt.Rock Roof Patche | http://steamcommunity.com/sharedfiles/filedetails/?id=1541438898
Vanilla Expanded Framework | http://steamcommunity.com/sharedfiles/filedetails/?id=2023507013
Perfect Pathfinding | http://steamcommunity.com/sharedfiles/filedetails/?id=2341486509
Change map edge limit | http://steamcommunity.com/sharedfiles/filedetails/?id=1546494565
Vanilla Events Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=1938420742
Vanilla Factions Expanded - Settlers | http://steamcommunity.com/sharedfiles/filedetails/?id=2052918119
Vanilla Furniture Expanded - Production | http://steamcommunity.com/sharedfiles/filedetails/?id=1880253632
Vanilla Furniture Expanded - Power | http://steamcommunity.com/sharedfiles/filedetails/?id=2062943477
Vanilla Factions Expanded - Vikings | http://steamcommunity.com/sharedfiles/filedetails/?id=2231295285
Vanilla Factions Expanded - Mechanoids | http://steamcommunity.com/sharedfiles/filedetails/?id=2329011599
Pick Up And Haul (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2277459062
ResearchPal - Forked | http://steamcommunity.com/sharedfiles/filedetails/?id=2351393394
Combat Training | http://steamcommunity.com/sharedfiles/filedetails/?id=1542761308
Rimworld: Altered Carbon | http://steamcommunity.com/sharedfiles/filedetails/?id=2196278117
World Map Beautification Project | http://steamcommunity.com/sharedfiles/filedetails/?id=2314407956
Death Rattle Continued [1.2] | http://steamcommunity.com/sharedfiles/filedetails/?id=2206107940
Human Power Generator Mod | http://steamcommunity.com/sharedfiles/filedetails/?id=1706030487
Turret Collection | http://steamcommunity.com/sharedfiles/filedetails/?id=1828462622
Roads of the Rim (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2280318231
MedPod | http://steamcommunity.com/sharedfiles/filedetails/?id=2153065191
QualityBuilder | http://steamcommunity.com/sharedfiles/filedetails/?id=754637870
[NL] Dynamic Portraits | http://steamcommunity.com/sharedfiles/filedetails/?id=2253730555
Achtung! | http://steamcommunity.com/sharedfiles/filedetails/?id=730936602
Doors Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=1316188771
Locks 2: Lock Them Out! | http://steamcommunity.com/sharedfiles/filedetails/?id=2285862824
Prison Labor | http://steamcommunity.com/sharedfiles/filedetails/?id=1899474310
Vanilla Weapons Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=1814383360
Vanilla Factions Expanded - Medieval | http://steamcommunity.com/sharedfiles/filedetails/?id=2023513450
Use Minified Buildings | http://steamcommunity.com/sharedfiles/filedetails/?id=2185809028
TMC Equipment - Combat Assist Goggles | http://steamcommunity.com/sharedfiles/filedetails/?id=2243681587
[CP] Prisoner Outfit | http://steamcommunity.com/sharedfiles/filedetails/?id=1507216525
Rimworld Search Agency (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2313268368
Hospitality | http://steamcommunity.com/sharedfiles/filedetails/?id=753498552
Vanilla Furniture Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=1718190143
Vanilla Furniture Expanded - Security | http://steamcommunity.com/sharedfiles/filedetails/?id=1845154007
Animal Gear | http://steamcommunity.com/sharedfiles/filedetails/?id=1541438907
Animal Armor: Vanilla | http://steamcommunity.com/sharedfiles/filedetails/?id=1743423205
Ugh You Got Me | http://steamcommunity.com/sharedfiles/filedetails/?id=1542424705
Home Mover | http://steamcommunity.com/sharedfiles/filedetails/?id=2092552843
Realistic Rooms | http://steamcommunity.com/sharedfiles/filedetails/?id=848972794
[FSF] Filth Vanishes With Rain And Time | http://steamcommunity.com/sharedfiles/filedetails/?id=1508341791
Medical Tab | http://steamcommunity.com/sharedfiles/filedetails/?id=715565817
Research Info | http://steamcommunity.com/sharedfiles/filedetails/?id=2290462337
More Utility Packs | http://steamcommunity.com/sharedfiles/filedetails/?id=2357611837
Blueprints | http://steamcommunity.com/sharedfiles/filedetails/?id=708455313
A Dog Said... Animal Prosthetics | http://steamcommunity.com/sharedfiles/filedetails/?id=746425621
Dubs Bad Hygiene | http://steamcommunity.com/sharedfiles/filedetails/?id=836308268
Animal Tab | http://steamcommunity.com/sharedfiles/filedetails/?id=712141500
Tilled Soil | http://steamcommunity.com/sharedfiles/filedetails/?id=725747149
Centralized Climate Control (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2007268173
[KV] RimFridge | http://steamcommunity.com/sharedfiles/filedetails/?id=1180721235
ToolBox | http://steamcommunity.com/sharedfiles/filedetails/?id=2016186459
Architect Expanded - Fences | http://steamcommunity.com/sharedfiles/filedetails/?id=2050680665
Door Mat | http://steamcommunity.com/sharedfiles/filedetails/?id=1505423207
Area Unlocker | http://steamcommunity.com/sharedfiles/filedetails/?id=725153576
Where is my weapon? | http://steamcommunity.com/sharedfiles/filedetails/?id=1539028008
Share The Load | http://steamcommunity.com/sharedfiles/filedetails/?id=1356838246
Wall Light | http://steamcommunity.com/sharedfiles/filedetails/?id=1423699208
[WD] Expanded Floors | http://steamcommunity.com/sharedfiles/filedetails/?id=1817862464
Harvest Organs Post Mortem | http://steamcommunity.com/sharedfiles/filedetails/?id=1204502413
Expanded Prosthetics and Organ Engineering | http://steamcommunity.com/sharedfiles/filedetails/?id=725956940
Smart Medicine | http://steamcommunity.com/sharedfiles/filedetails/?id=1309994319
Veinminer R1.1 | http://steamcommunity.com/sharedfiles/filedetails/?id=1541978411
Electric Stonecutting Table | http://steamcommunity.com/sharedfiles/filedetails/?id=1649368867
Underground Power Conduits | http://steamcommunity.com/sharedfiles/filedetails/?id=1735421319
[WD] Reinforced Doors | http://steamcommunity.com/sharedfiles/filedetails/?id=1857597307
Advanced Shield Belts | http://steamcommunity.com/sharedfiles/filedetails/?id=1417354001
Chemicals & Neutroamine | http://steamcommunity.com/sharedfiles/filedetails/?id=765351437
Map Wide Orbital Trade Beacon | http://steamcommunity.com/sharedfiles/filedetails/?id=1839069104
LWM's Deep Storage | http://steamcommunity.com/sharedfiles/filedetails/?id=1617282896
Dubs Mint Menus | http://steamcommunity.com/sharedfiles/filedetails/?id=1446523594
Trap Disable | http://steamcommunity.com/sharedfiles/filedetails/?id=1542019602
[FSF] Better Spike Traps | http://steamcommunity.com/sharedfiles/filedetails/?id=1459119465
More Vanilla Turrets 1.1 | http://steamcommunity.com/sharedfiles/filedetails/?id=2009766414
No Forced Slowdown | http://steamcommunity.com/sharedfiles/filedetails/?id=1419593453
[WD] Barbed Wire | http://steamcommunity.com/sharedfiles/filedetails/?id=1501655249
[SYR] Neuter | http://steamcommunity.com/sharedfiles/filedetails/?id=1501449584
Floor Lights | http://steamcommunity.com/sharedfiles/filedetails/?id=1541728186
MinifyEverything | http://steamcommunity.com/sharedfiles/filedetails/?id=872762753
Tabletop Trove - Additional Joy Objects and Decor | http://steamcommunity.com/sharedfiles/filedetails/?id=1961528842
Character Editor | http://steamcommunity.com/sharedfiles/filedetails/?id=1874644848
No Sympathy for Prisoners | http://steamcommunity.com/sharedfiles/filedetails/?id=2167490674
Simple sidearms | http://steamcommunity.com/sharedfiles/filedetails/?id=927155256
Stack XXL | http://steamcommunity.com/sharedfiles/filedetails/?id=826366050
Hunters Use Melee! | http://steamcommunity.com/sharedfiles/filedetails/?id=2062709324
Bulk Stonecutting | http://steamcommunity.com/sharedfiles/filedetails/?id=2021425587
RT Solar Flare Shield | http://steamcommunity.com/sharedfiles/filedetails/?id=728315620
Common Sense | http://steamcommunity.com/sharedfiles/filedetails/?id=1561769193
Giddy-up! Caravan | http://steamcommunity.com/sharedfiles/filedetails/?id=1253251478
Giddy-up! Ride and Roll | http://steamcommunity.com/sharedfiles/filedetails/?id=1331961995
TradeHelper | http://steamcommunity.com/sharedfiles/filedetails/?id=2113372560
Keep Bed Ownership | http://steamcommunity.com/sharedfiles/filedetails/?id=2130184293
Plasteel Surgery (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2018276375
[PS] Reconditioning Pod (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2044003955
Herd Migration Revival(revived) | http://steamcommunity.com/sharedfiles/filedetails/?id=2090177060
Days Matter (fork) | http://steamcommunity.com/sharedfiles/filedetails/?id=2045496988
[1.2] Simple Recycling | http://steamcommunity.com/sharedfiles/filedetails/?id=2079862064
[WD] Fast Moisture Pumps | http://steamcommunity.com/sharedfiles/filedetails/?id=1164753788
Preemptive Strike (Fork) | http://steamcommunity.com/sharedfiles/filedetails/?id=2056230561
Quarry 1.1 | http://steamcommunity.com/sharedfiles/filedetails/?id=2007576583
Vanilla Books Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=2193152410
Vanilla Brewing Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=2186560858
Vanilla Cooking Expanded | http://steamcommunity.com/sharedfiles/filedetails/?id=2134308519
No more sleeping Z's | http://steamcommunity.com/sharedfiles/filedetails/?id=2024071585
Smarter Construction | http://steamcommunity.com/sharedfiles/filedetails/?id=2202185773
[KV] More Trait Slots | http://steamcommunity.com/sharedfiles/filedetails/?id=1508292711
RPG Style Inventory | http://steamcommunity.com/sharedfiles/filedetails/?id=1561221991
Realistic Prosthetics Expansion | http://steamcommunity.com/sharedfiles/filedetails/?id=1498483853
More Planning | http://steamcommunity.com/sharedfiles/filedetails/?id=881100382
RT Fuse | http://steamcommunity.com/sharedfiles/filedetails/?id=728314182
Mod Manager | http://steamcommunity.com/sharedfiles/filedetails/?id=1507748539
Better Workbench Management | http://steamcommunity.com/sharedfiles/filedetails/?id=935982361
Everybody Gets One | http://steamcommunity.com/sharedfiles/filedetails/?id=1687566130
Show Draftees Weapon | http://steamcommunity.com/sharedfiles/filedetails/?id=1690978457
Outfitted | http://steamcommunity.com/sharedfiles/filedetails/?id=1595812861
Pharmacist | http://steamcommunity.com/sharedfiles/filedetails/?id=1365242717
Compact Hediffs | http://steamcommunity.com/sharedfiles/filedetails/?id=2031734067
RunAndGun | http://steamcommunity.com/sharedfiles/filedetails/?id=1204108550
Best Mix (Continued) | http://steamcommunity.com/sharedfiles/filedetails/?id=2195986094
Heat Map | http://steamcommunity.com/sharedfiles/filedetails/?id=947972722
ShowModDesignators | http://steamcommunity.com/sharedfiles/filedetails/?id=1399212509
MiningCo. MMS | http://steamcommunity.com/sharedfiles/filedetails/?id=755224256

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [ ] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
@blkarcher77
* Without clear, consistent reproduction steps, it's very difficult (or even impossible) for me to try to fix this issue
* Please start a new, temporary savegame with only Harmony, Core and MedPod, and confirm that the issue does not occur
* You need to reduce your modlist down to the bare minimum number of mods required to cause this issue

**Comment by sumghai** [comment]
As the reporting user has not been able to reliably reproduce this issue with only the relevant mods required, there's not much I can do.

Closing for now, unless the user has new information to offer.
