### ISSUE TITLE
Simplify Traditional Chinese translation for Delta Wave Induced Coma

### ISSUE THREAD

**Issue by shiuanyue** [sumghai/MedPod#5]
~delta wave induced coma的繁體翻譯很繞口~

~不如跟cortical stimulation作個整合用詞，翻成大腦皮質麻醉如何?~
~我個人是會翻成腦波麻醉跟腦波刺激~

_Edit by sumghai - issue title and description translated to English:_

The Traditional Chinese translation for "delta wave induced coma" is very awkward.

How about something similar to what you already have for "cortical stimulation"? (e.g. 大腦皮質麻醉)
Personally, I would use 腦波麻醉 for "delta wave induced coma" (lit. "brain wave coma") and 腦波刺激 for "cortical stimulation" (lit. "brain wave stimulation")

**Comment by sumghai** [comment]
That's an excellent suggestion. 腦波麻醉 and 腦波刺激 definitely sounds much more straightforward.

By the way, in the future, please only submit issues in English (even for translation-related issues). Although I personally can understand Mandarin, English is the lingua franca of open-source projects, and I'd like to keep it that way for all of my repositories.

**Comment by sumghai** [comment]
Translations updated.

I decided to only simplify the hediff labels, while the hediff descriptions should continue to have the detailed references to delta waves, cerebral cortex etc.
