### ISSUE TITLE
Pawns will not start tasks.

### ISSUE THREAD

**Issue by EJeff21** [sumghai/MedPod#53]
**Describe the bug:**  

When starting the game pawns aren't able to commit any other action than wandering, eating, and sleeping. The player is unable to open/force tasks for the pawns. (such as selecting a pawn, then right clicking to force task.) Most vanilla game functions cease.
**Expected behavior:**  

Normal gameplay.
**Steps to reproduce:**  

1.Start a new game.
2.Designate an action for the pawn to complete. (i.e. mining, cooking, hauling, plant cutting.)
3.Select any pawn, then attempt to right click on the action.

**Additional information:**

Could not find type named MedPod.JobGiver_PatientGoToMedPod 
Exception loading list element from XML: System.MissingMethodException: Default constructor not found for type Verse.AI.ThinkNode
Could not find a type named MedPod.WorkGiver_DoctorRescueToMedPod
Could not find a type named MedPod.WorkGiver_WardenRescueToMedPod
Key binding conflict: Dev_ChangeSelectedDebugAction and MainTab_Architect are both bound to Tab.

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:** 32.0 GB
**RimWorld base game version:** 1.2.3062
**RimWorld DLCs loaded:** Royalty
**MedPod mod version:** 1.3.0
**MedPod mod downloaded from:** Steam
**Your mod list:** 
Harmony 1.1.1, Core, MedPod 1.3.0
## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Ah, I think I know what's going on!

You're running RimWorld 1.2, and while MedPod mod is loading the appropriate version of its assembly, it's currently also loading various Defs referencing class names intended for 1.3 (because they're sitting in a `Common` folder).

While I'm not going to backport the Work/JobDriver rewrite, I should at the very least be able to fix the 1.2 version back to the way it was. Might take a few days, though.

**Comment by sumghai** [comment]
Should be fixed now for the next update - tested successfully on both RW 1.2 and 1.3.
