### ISSUE TITLE
Patients die of thirst - see #35

### ISSUE THREAD

**Issue by FGRemastered** [sumghai/MedPod#54]
**Describe the bug:**  
The dehydration hediff from DubsBadHygiene causes pawns to die while in the Med(/Vet)Pod

**Expected behaviour:**  
The Thirst need should be treated the same as the hunger need

**Steps to reproduce:**  
1. Have a pawn get stuck in the machine, one way or another
2. wait
3. see

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
You modified the bug reporting template to omit the **System and Game Configuration** section, which means you have not provided all the information required, just like last time with the Scaria bug report.
![invalid report](https://user-images.githubusercontent.com/4993380/131498896-0b1adb31-f449-428d-803e-eaccc74579a9.png)

Please submit a new report and follow the template exactly as provided.
