### ISSUE TITLE
Android Tiers VX3 implants cause pawns to get stuck in MedPods

### ISSUE THREAD

**Issue by bakudo6** [sumghai/MedPod#55]
**Describe the bug:**  

I was trying to get my pawns to use the Medpods and they would, and now the pods aren't healing injuries like "leg burned off" while in the machine, then they'd stay in them until I aborted the process. after I aborted the process, it would show that the "leg burned off" injury was healed.

**Expected behavior:**  

they would use it and exit after being fully healed without any interaction from me.

**Steps to reproduce:**  

1. use prepare carefully to start pawn(s) with VX3 chips already installed in them and start game.
2. build a powered medpod. 
3. injure pawns to the point they need to use it and observe.

**Additional information:**

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:** 32 GB
**RimWorld base game version:** 1.3.3102
**RimWorld DLCs loaded:** Royalty & Ideology
**MedPod mod version:** 1.3.1
**MedPod mod downloaded from:** Steam
**Your mod list:** Harmony 1.3, Core, Royalty, Ideology, HugsLib 9.0.0, Humanoid Alien Races 1.3, Enable Oversized Weapons 1.3, Android Tiers 3.0.0RC rev3, EdB Prepare Carefully 1.3.8, Medpod 1.3.1      

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
It looks like the VX series of implants adds a couple of hidden hediffs - `Solar Flare` and `Low Network Signal` - which affect pawn consciousness. Between 1.2 and 1.3, these hediffs were modified with `isBad` set to `true` and custom hediff classes, which I suspect is probably conflicting with the MedPod's own induced coma.

The solution seems to be to just tell the MedPods to ignore these hediffs during treatment.

**Comment by sumghai** [comment]
Should be fixed now.
