### ISSUE TITLE
Guestmode

### ISSUE THREAD

**Issue by FGRemastered** [sumghai/MedPod#64]
**Describe your idea:**

A button to allow visitors to use certain MedPods by themselves. (Maybe for a price with Orion's Hospitality in mind?)

**Why do you think your idea would be a good fit for MedPod?:**
You can already force your pawns to carry downed guests to the MedPod, so why not offer them as a service to them? (And make some money on the side perhaps?)

**What alternatives/workarounds have you tried?**
Forcing pawns to carry guests to the MedPod.

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
Oooh, this sounds interesting.

> You can already force your pawns to carry downed guests to the MedPod

I haven't dealt much with guest/visitors myself, but I assume this is just with the base game? (And not the Hospitality mod?)

If so, I could potentially look into patching guest ThinkTrees to include a `MedPod.JobGiver_PatientGoToMedPod` node, and possibly add a gizmo that would allow individual MedPods to be allow/prohibit guests from using them.

As for integration with Hospitality's payment system, I'm not sure how this would work thematically. While MedPods are free for public use on GlitterWorlds, they would be very valuable/coveted resources on RimWorlds, so players should charge really high prices for MedPod treatment.

I could add a new MedPod computer building that is mainly used to manage payment via a slider gizmo ($0 to $100~1000), but I'm not sure what would happen if the guest doesn't have that much silver on them.

**Comment by FGRemastered** [comment]
> I haven't dealt much with guest/visitors myself, but I assume this is just with the base game? (And not the Hospitality mod?)

Correct, as described in the other open issue, it would also be nice for pawns that hold another to have an interaction with the MedPod to transfer the held pawn onto it, btw.

Hospitality has an extra library mod of sorts, called Orion's Cash Register or similar, that handles the payment part, so you'd only need to add another tab to its ui instead of writing a new building. It also determines what happens if they don't have the money - They can't use it. Maybe add a dialogue for them to ask for a one-time cost decrease if they can't afford it, but are in pain, for example?

Now that I think about it, there could also be room for a new kind of beggars quest that came with ideology: Normally beggars ask you for medicine, drugs or money, but what if they asked for a chance to use the fancy heal-all building instead?

**Comment by sumghai** [comment]
We'll worry about stretch goals later - if I do tackle this, my first priorities are to allow guests to use the MedPods on their own accord, and to allow players to specify which MedPods are available to guests.

**Comment by Astr0Jack** [comment]
my colonists forcefully shove guests into the medpod, and i dont want my guests to be happy

**Comment by sumghai** [comment]
I found some time recently to revisit this idea.

My current WIP implementation adds an "Allow guests" gizmo to MedPods, logic changes to mark MedPods with the correct guest flag state as usable by friendly non-colony visitors from the base game, and a ThinkTree patch that tells visitors to seek MedPod treatment if required. 

However, this results in the following problems:
- A caravan trader or visitor with items to trade (denoted by a yellow question mark mote) who use a MedPod will immediately lose their trader status and leave the map, denying players trading opportunity
- Caravan guards and companions who use MedPods will also automatically leave the map, often taking with them trader inventory that the player might be interested in

Allowing free treatment for NPC visitors at the cost of immediately preventing players from trading with them sounds like a pretty terrible outcome.

I now have two options:
1. Somehow figure out how to **_not_** trigger the leave signal for NPC pawns after MedPod treatment, and additionally retain/restore the trader pawn's job
2. Limit this guest mode feature to the Hospitality and Hospital mods (which would handle the ThinkTree patch on their end)

Thoughts?

**Comment by sumghai** [comment]
I've decided to remove the thinktree patch for base game traders and visitors, as allowing them to use MedPods would cause them to automatically leave.

Instead, I'll focus my attention on possible guest mode compatibility with the Hospital and Hospitality mods.

**Comment by sumghai** [comment]
WIP notes for MedPod compatibility with Hospital mod (https://github.com/tomvd/Hospital/)

- [x] Hospital mod already patches their Patient DutyDef to add `MedPod.JobGiver_PatientGoToMedPod`
- [x] Add gizmo, savable boolean flag, and additional conditional checks to allow friendly non-colonists to use MedPods
- [ ] Set default `Hospital Bed` and `Surgery Bed` gizmos and boolean flag state to `false` for all MedPods and VetPods (justification: MedPods are very power hungry)
- [ ] Hide `Surgery Bed` gizmo and permanently disable surgeries on all MedPods (justification: MedPods are never intended for surgeries)
- [ ] Use `Hospital Bed` gizmo to directly drive `Building_BedMedPod`'s internal `public allowGuests` boolean (and hide the now-redundant `Allow Guests` gizmo from the MedPod mod itself)

**Comment by sumghai** [comment]
WIP notes for MedPod compatibility with Hospitality mod (https://github.com/OrionFive/Hospitality/)
- [ ] Add / fix conditional checks to allow Hospitality guests to seek use MedPods
- [ ] Patch Hospitality mod Relax DutyDef to add `MedPod.JobGiver_PatientGoToMedPod`

**Comment by sumghai** [comment]
The code I committed so far allows Hospitality guests to use MedPods within Hospitality's allowed guest area and with the `Allow Guests` gizmo enabled. However, guests that complete MedPod treatment lose their Hospitality guest duty and assigned guest bed due to being "downed" by the MedPod's delta wave coma hediff, forcing them to rejoin the existing visitor group afterwards and then complain about running out of money to re-reserve a bed. 

This is pretty much the same as what happened to base game traders and visitor groups, as mentioned in prior comments.

Removing the delta wave coma and cortical stimulation hediffs ensures that existing lords and duties are retained, but pawns tend to run off towards the end of treatment, such that the `WakePatient()` method with all the pawn needs, traits and worktypes cleanup calls are never run. It seems that there is an end condition being triggered:

```
6119573 Pree: JobDriver_PatientGoToMedPod ends current job PatientGoToMedPod (Job_265106) A = Thing_MedPodStandard263597 Giver = JobGiver_PatientGoToMedPod [workGiverDef: null] because of toil LayDown at toils[2].endConditions[0]
```

I'll need to figure out how to modify this end condition to not fail until MedPod treatment is fully complete and `WakePatient()` has been run.

**Comment by sumghai** [comment]
I think I've revised the treatment cycle to not use the delta-wave induced coma hediffs, and run `DischargePatient()` (formerly `WakePatient()`) when the resting job is terminated for any reason. Probably needs a bit more playtesting to confirm that the new logic is reliable, though.

**Comment by sumghai** [comment]
Save for some minor unrelated bugs that still need to be addressed, this added gizmo and logic rewrite now supports Allowing/Disallowing non-colony Guests from vanilla and the Hospitality mod.

The Hospital mod is now also technically supported, but additional patches are recommended to tie the MedPod's guest status better with the Hospital mod's own Hospital bed gizmo. I'll most likely have to discuss this with @tomvd some other time.
