### ISSUE TITLE
Error in main menu when Vanilla Expanded Cooking mod is enabled

### ISSUE THREAD

**Issue by nemomode7** [sumghai/MedPod#68]
**Describe the bug:**  
 
If mod "[Vanilla Cooking Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519)" is enabled I'm getting error message in main menu.

**Expected behavior:**  No errors
 

**Steps to reproduce:**  

1. Load and enable VE Cooking and dependencies
2. Load and enable MedPod 

**Additional information:**

With only VEC and MP loaded.
![RimWorldWin64_VUkCel5U9A](https://user-images.githubusercontent.com/46643755/197390730-9b578d45-66e3-4234-b401-9dcdedbe9998.png)

With VEC, MP and some more mods loaded. 
**_Note, the if i disable either VEC or MP the errors are gone frome the main menu._** Full log for this case is [here](https://gist.github.com/HugsLibRecordKeeper/008a9af0c304a04cc3f6206841e5ba4e). 
VEC's devs take on this case: "You have another mod that is trying to reference Diabetes, Cholesterol and High Blood Pressure, which were removed from 1.4, and no longer exist in this mod".
![RimWorldWin64_SzVf0M59ul](https://user-images.githubusercontent.com/46643755/197390732-eaf80ff1-9ebd-4921-a258-7fdffd476def.png)

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit) 
**Physical RAM:** 32 GB 
**RimWorld base game version:** 1.4.3525 
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech 
**MedPod mod version:** 1.5.0 
**MedPod mod downloaded from:** Steam 
**Your mod list:** Testing case": Harmony 2.2.2.0,  Latest Vanilla Expanded Framework, Latest Vanilla Expanded Cooking", Second case - can be found in the [full log](https://gist.github.com/HugsLibRecordKeeper/008a9af0c304a04cc3f6206841e5ba4e). 

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
@nemomode7 - Please try the following development build of MedPod:

https://github.com/sumghai/MedPod/archive/b72cd553c6a7ae93248822731600a556e947f066.zip

**Comment by sumghai** [comment]
The Steam user who originally reported the bug (without filing a GitHub issue) has since verified the dev build fixes the issue, so we can mark this one as done.
