### ISSUE TITLE
Babies from Biotech DLC stuck in a treatment loop on MedPods

### ISSUE THREAD

**Issue by frovoc** [sumghai/MedPod#69]
**Describe the bug:**  
My people keep carrying infants into the medpod for no reason and i have no way to prevent them from doing so unless forbid medpod, im getting messages every few seconds about it, thats quite annoying.

**Expected behavior:**  
Please fix the status detection for infants.

**Steps to reproduce:**  

1. Have an infant
2. Let the baby have a bad state of health
3. Use medpod to treat it.
After a successful treatment, the problem I described should keep happening

**Additional information:**

Console has no error report, but thats quite annoying.

i test with few mods again, it still happened.[the mod i used are list as following. ]  

i start a quick test and give bady a **food poision** status, the problem I described happened again.

{modlist:
Harmony -Steam newest version
core 
royalty
idology
biotech
medpod 1.5.1
}
## System and Game Configuration
**Operating System:** 
win11
**Physical RAM:** 
16gb
**RimWorld base game version:** 
1.4.3525
**RimWorld DLCs loaded:** 
All
**MedPod mod version:** 
1.5.1
**MedPod mod downloaded from:** 
Steam
**Your mod list:** 
Harmony -Steam newest version
core 
royalty
idology
biotech
medpod 1.5.1

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
@frovoc - Your bug report is incomplete.

- What are your system specifications?
- What version and build number of the game are you running?
- Which DLCs do you have loaded? Which version of MedPod are you running?
- Can the issue be reproduced with as few mods and DLCs as possible on a new, temporary save?
- What specific hediff did you apply to the child?
- Did you complete the declaration for the bug report?

Please edit your original comment with the missing info.

**Comment by frovoc** [comment]
[testMedpod.zip](https://github.com/sumghai/MedPod/files/9850065/testMedpod.zip)
this is the save.

**Comment by frovoc** [comment]
and thans for work again, it is a great mod.

**Comment by sumghai** [comment]
> Did you complete the declaration for the bug report?
> yes?
You need to tick the checkboxes in the declaration section.

**Comment by sumghai** [comment]
Should be fixed for the next update.
