### ISSUE TITLE
Sanguophage from biotech DLC carried to medpod when deathresting

### ISSUE THREAD

**Issue by Hamacia** [sumghai/MedPod#70]
**Describe the bug:**  

Sanguophage is being taken from deathrest casket to medpod until deathrest is complete. Even If I take him out of the medpod back to the casket he will be carried back to the medpod. It is annoying since the medpod does not have the deathrest acceleration so extra time is used at the medpod compared to the casket.

**Expected behavior:**  

Please add deathrest exception to medpod or option to apply deathrest casket buffs to the medpod.

**Steps to reproduce:**  

1. Have sanguophage
2. Sanguophage goes to deathrest at casket
3. Sanguophage carried to medpod until deathrest is complete or medpod is forbidden until deathrest can be properly completed at casket

**Additional information:**

I did not see any errors on debug log

## System and Game Configuration
**Operating System:** 
Win10
**Physical RAM:**
32gb 
**RimWorld base game version:** 
1.4.3529
**RimWorld DLCs loaded:** 
All
**MedPod mod version:** 
1.5.1
**MedPod mod downloaded from:** 
steam
**Your mod list:** 
Harmony -Steam newest version
core
royalty
idology
biotech
medpod 1.5.1
## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Already fixed in the recent v1.5.2 update - please update your mods.
