### ISSUE TITLE
MedPod appears to be stuck.

### ISSUE THREAD

**Issue by ruifung** [sumghai/MedPod#71]
**Describe the bug:**  

Colonist has smokeleaf withdrawal 100%, gets stuck in medpod

**Expected behavior:**  

For it to not get stuck in the medpod.
In the meantime, I'll just use devmode to remove it.

**Steps to reproduce:**  

1. I'm not entirely sure what causes it, but the pawn has smokeleaf withdrawal at 100%
2. Pawn gets into medpod
3. MedPod gets stuck.

**Additional information:**

![image](https://user-images.githubusercontent.com/1073945/201287949-1b5adf44-1cc4-46af-86a8-992a41dde55c.png)
![image](https://user-images.githubusercontent.com/1073945/201287986-c3588e39-9983-4956-a16d-28168249714f.png)

## System and Game Configuration
**Operating System:** Microsoft Windows 11 (64-bit) 22H2 Build 22621.674
**Physical RAM:** 32GB
**RimWorld base game version:** 1.4.3542
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech
**MedPod mod version:** v1.5.3
**MedPod mod downloaded from:** Steam
**Your mod list:** 
https://gist.github.com/HugsLibRecordKeeper/a3bc89e20ff0ca9975ed7a260d6ce7b1

## Declaration

I hereby verify that:
- [X] I am running the latest version of the game, MedPod and its dependencies
- [ ] I am NOT running any mods with known incompatibilities with MedPod
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [ ] I have confirmed that the issue does not happen if MedPod is disabled
- [X] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [X] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Why haven't you narrowed down your modlist?
![image](https://user-images.githubusercontent.com/4993380/201298137-d95cc6d8-a89e-44e5-904d-4c5c8b44f6b7.png)

**Comment by ruifung** [comment]
Just tried to reproduce with dev tools, can't seem to reproduce. Even with the full mod list.
Wierd.
