### ISSUE TITLE
XML Verse.HediffDef defines the same field twice: isBad.

### ISSUE THREAD

**Issue by 893821846** [sumghai/MedPod#74]
**Describe the bug:**  

I'm sure this mod has caused a lot of such errors when it was added. These errors seem to be related to Android robots：
<HediffDef ParentName="ChJAndroidUpgradeBase"><everCurableByItem>false</everCurableByItem><isBad>false</isBad><countsAsAddedPartOrImplant>true</countsAsAddedPartOrImplant><isBad>false</isBad><defName>ChjAndroidUpgrade_Hulking</defName><description>Gives the Android an hulking and strong physique. The Android is now better at physically demanding tasks.\n-- "Hulk smash!"</description><label>hulking physique upgrade</label><defaultLabelColor>(0.0, 0.8, 0.8)</defaultLabelColor><stages><li><statOffsets><CarryingCapacity>85</CarryingCapacity><ArmorRating_Sharp>0.5</ArmorRating_Sharp><ArmorRating_Blunt>3</ArmorRating_Blunt><CarryWeight>40</CarryWeight><CarryBulk>20</CarryBulk></statOffsets><capMods><li><capacity>Manipulation</capacity><postFactor>1.5</postFactor></li></capMods></li></stages><modExtensions><li Class="Androids.AndroidUpgradeHediffProperties"><def>Upgrade_HulkPhysique</def></li></modExtensions></HediffDef>
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
XmlExtensions.CustomXmlLoader:ObjectFromXml<Verse.HediffDef> (System.Xml.XmlNode,bool,System.Xml.XmlNode,string)
XmlExtensions.CustomXmlLoader:ObjectFromXmlReflection<Verse.HediffDef> (System.Xml.XmlNode,bool)
(wrapper dynamic-method) Verse.DirectXmlLoader:Verse.DirectXmlLoader.DefFromNode_Patch2 (System.Xml.XmlNode,Verse.LoadableXmlAsset)
(wrapper dynamic-method) Verse.LoadedModManager:Verse.LoadedModManager.ParseAndProcessXML_Patch3 (System.Xml.XmlDocument,System.Collections.Generic.Dictionary`2<System.Xml.XmlNode, Verse.LoadableXmlAsset>)
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Expected behavior:**  

no error report?
**Steps to reproduce:**  

1.run those mod:Harmony;core;dlc for three;Hugslib;humanoid alien races;androids for rw 1.4;medpod;
2.then ,when u are in game menu,those error report happened
3.

**Additional information:**

## System and Game Configuration
**Operating System:** microsft windows 11 64-bit
**Physical RAM:** 32gb
**RimWorld base game version:** latest
**RimWorld DLCs loaded:** all
**MedPod mod version:** latest
**MedPod mod downloaded from:** steam
**Your mod list:** Harmony;core;dlc for three;Hugslib;humanoid alien races;androids for rw 1.4;medpod;all latest

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Please provide the missing information in your bug report:

![image](https://user-images.githubusercontent.com/4993380/210626410-335a96fb-9f01-4ba5-a064-87e0c80417e1.png)

**Comment by 893821846** [comment]
hope those help,Sorry about the missing information last time

**Comment by sumghai** [comment]
This bug will be fixed in the next update.

> hope those help,Sorry about the missing information last time

![image](https://user-images.githubusercontent.com/4993380/210710240-98646e19-a187-4f77-85cb-f6d3e913650e.png)
In the future, please write down the **_exact_** version numbers of the base game and mods. This is because some bugs may only happen in specific game/mod versions, and without the correct version numbers I could potentially be wasting time chasing down bugs that were already fixed in newer versions.

Please familiarize yourself with the following section on how to write a good bug report:
https://gist.github.com/sumghai/71da62f9f4a3c8f377acd1fd9655e6de#step-7-submit-a-bug-report
