### ISSUE TITLE
vet pod stuck in idle

### ISSUE THREAD

**Issue by yowshi** [sumghai/MedPod#75]
**Describe the bug:**  
I had a downed elephant get rescued, instead of dragging it directly to the mega vetpod it gets dragged to an animal bed, where it then teleports to the vetpod. which proceeds to sit in idle with the downed elephant ontop of it.

**Expected behavior:**  
downed animals should just get draged to the vetpod right?

**Steps to reproduce:**  

get a large animal.
down it some how.
rescue it.

i've run other tests using a character editor mod, i can't get animals to get dragged to the vetpod.

**Comment by sumghai** [comment]
Lots of information are missing from this bug report. Please perform proper troubleshooting, follow the proper bug reporting template and try again.
