### ISSUE TITLE
More difficulty setting

### ISSUE THREAD

**Issue by databobek** [sumghai/MedPod#76]
**Describe your idea:**
 Consider adding a "hardcore mode" setting to the mod, that will increase the build and operating costs of the medpod(s). Currently they're quite easily obtainable (especially when combined with other mods) thus making the game a bit too easy. Consider adding a slider increasing/decreasing MedPod treat time.

**Why do you think your idea would be a good fit for MedPod?:**
MedPod is one of my favourite mods, however I always find myself tweaking it to be less accessible. I think many people choose not to use it at all because it feels OP at the cost/result ratio.

**What alternatives/workarounds have you tried?**
I've made a patch for myself to increase the costs of the MedPod. It is linked to AoTC mod (because I use it, so in my case it made sense).
`	<costList>
			<SNS_Component_GenII>12</SNS_Component_GenII>
			<Nanomachinery>8</Nanomachinery>
			<IsolinearProcessor>1</IsolinearProcessor>
			<SNS_Unobtainium>200</SNS_Unobtainium>
			<SNS_CosmicAlloy>80</SNS_CosmicAlloy>
		</costList>
`
`<basePowerConsumption>50000</basePowerConsumption>`
and the research takes  a few months to complete.

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
https://github.com/sumghai/MedPod/wiki/FAQ#q-could-you-add-mod-options
