### ISSUE TITLE
Pawns drop sidearms when anesthetized and uses MedPod

### ISSUE THREAD

**Issue by MoodyBlueSkies** [sumghai/MedPod#77]
**Describe the bug:**  
After an operation done on a pawn, they are taken to the MedPod to cure them of being anesthetized. When the pawn is placed, they drop their sidearm and the sidearm immediately becomes forbidden.

**Expected behavior:**  
I expected the sidearms from the Simple Sidearms mod to stay with the pawn as they were being treated for the anesthetized hediff, like how the weapon would stay in a pawn's inventory before I downloaded Simple Sidearms.

**Steps to reproduce:**  
1. Operate on pawn to completion **or** anesthetize a pawn
2. Let the anesthetized pawn be taken to a MedPod
3. Watch as the pawn drops a weapon once placed

**Additional information:**
![image](https://github.com/sumghai/MedPod/assets/69198251/bf9c4894-2583-48f9-a832-399972b10dfa)
![image](https://github.com/sumghai/MedPod/assets/69198251/bcaa495e-5516-4d65-8b39-8f6293a2e6c0)
![image](https://github.com/sumghai/MedPod/assets/69198251/52280f82-ca0f-41b7-86cd-40474dd8a1fd)
![image](https://github.com/sumghai/MedPod/assets/69198251/70758960-3fef-4781-873b-4fc63f5c9cee)
![image](https://github.com/sumghai/MedPod/assets/69198251/41d5f17c-e760-4702-95ed-8d87d486b3d0)

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.4.3704
**RimWorld DLCs loaded:** Royalty, Biotech, 
**MedPod mod version:** 1.5.10
**MedPod mod downloaded from:** GitHub
**Your mod list:** Actually Vanilla Music Expansion, Harmony, Core, Performance Optimizer, Startup impact 1.4, Performance Fish, Royalty [Official DLC], Ideology [Official DLC], Biotech [Official DLC], HugsLib v10.0.1, RocketMan - Performance Mod, Dubs Performance Analyzer, Mod Options Sort, Mod Error Checker, Mid-saver Saver, Common Sense, Vanilla Expanded Framework, Athena Framework, JecsTools v1.4.1., Map Preview, Camera+, RimHUD v1.10.3, BetterInfoCard, Dubs Mint Menus, Toggleable Overlays, [LTO] Colony Groups, Giddy-Up 2, [NL] Facial Animation – WIP, Vee face for Facial Animation, Muzzle Flash, Verbose, Same Room Lovin', Bunk Beds, Loft Bed, One bed to sleep with all, Polyamory Beds (Vanilla Edition), Expanded Prosthetics and Organ Engineering - Forked v4.3.5, **MedPod v1.5.10**, **Simple sidearms v1.6.2**, Research Tree, Smarter Construction, Smarter Deconstruction and Mining, Share The Load, Colonist Bar Below Dev Buttons, EdB Prepare Carefully v1.4.3, Harvest Everything!, [CAT] Show Hair With Hats or Hide All Hats, Gradient Hair, [1.4] Lovely Hair Style, Won hair_men, Dubs Apparel Tweaks, Character Editor v1.4.1240, [Kit] Graze up, More Faction Interaction (Continued), Humanoid Alien Races, Kurin, The Three Tailed Fox [Deluxe Edition], Doors Expanded v1.4.1.1, Misc. Training, Better Pyromania, Choice Of Psycasts, Vanilla Textures Expanded, More Vanilla Textures, Better Vanilla Masking, RimStory (Continued) v1.1, Conduit Deconstruct, CM Color Coded Mood Bar [1.1+], Moody, Follow Me v3.5.76, Relations Tab v2.3.68, Medical Tab v2.12.86, Power Tab 2, Pharmacist (Forked with blood rot fix), Beautiful Bodies, Harvest Organs Post Mortem, Medical Dissection v2.8, Death Rattle [1.4], Stabilize, Smart Speed, Smart Farming, Prisoners Dont Have Keys, Prison Commons (Continued), Restraints, Enhanced Vat Learning, RimFridge Updated, LWM's Deep Storage, [sd] Advanced Power generation (Continued), Tilled Soil, BetterVents, Wall Light, No more sleeping Z's v1.1, Stop, Drop, And Roll! [BAL], Ugh You Got Me v1.0.7, RunAndGun, RPG Style Inventory v5.0, Quest Reward Rebalance, Roads of the Rim (Continued), Convert Then Recruit v2.5, Interaction Bubbles, Improved Wastepack Atomizer, More Trade Ships (Continued), Simple FX: Splashes, Simple FX: Vapor, More Planning [1.4], Bionic icons, Trait and Backstory Icons, Moonlight, Therapy, Vanilla Persona Weapons Expanded, Reunion, Hardworking animals 1.4, Just Put It Over There, Veinminer R1.1 v1.2, Skilled Stonecutting [1.4], RT Solar Flare Shield, Gene Ripper, Faux's Xenotype Icons, Literally just a sofa, Grimworld: Melee, Electric Stonecutting Table, RT Fuse, Randomised Stone Refinery, Better ground-penetrating scanner, Victorian Era Apparels!, [CP] Prisoner Outfit, Door Mat, RuntimeGC [1.4], The Most Powerful Dog!, MendAndRecycle, [FSF] Filth Vanishes With Rain And Time 
Note: Not a lot of the mods show their versions.

## Declaration
I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Cut your mod list down to less than than 5 mods and/or DLCs, and if you can reproduce your issue under those circumstances, let me know.

**Comment by MoodyBlueSkies** [comment]
Hi there. I've limited the mods I have to Core, Biotech, Harmony, Simple Sidearms, and MedPod. Hope this helps.

![image](https://github.com/sumghai/MedPod/assets/69198251/86308c68-bff4-4ea0-ae8a-4abf4767f3df)
![image](https://github.com/sumghai/MedPod/assets/69198251/c3d95e2c-cc8e-49e8-aeeb-1b8af6236f2e)
![image](https://github.com/sumghai/MedPod/assets/69198251/1bb54966-71ac-41a1-80b2-daa53d355675)

**Comment by sumghai** [comment]
Unfortunately, this is actually a bug in the base game itself - I was able to reproduce the behavior with no mods at all, just Core (RW 1.4.3704).

When any pawn that is downed or incapable of walking gets carried by another pawn to any bed, they will always drop their weapons and inventory. This can be reproduced as follows:

1) Enable God Mode
2) Construct two regular single beds
3) Equip a pawn with a weapon
4) Assign the Anesthetize operation to the pawn
5) Let the pawn walk to one bed and be anesthetized
6) Uninstall the pawn's current bed - their weapon will stay in inventory
7) Let another pawn carry the downed pawn to the second bed - the downed pawn will automatically drop their weapon

As this is a problem with the base game itself, there is nothing I can do about it. Please join the [Rimworld official development Discord server](https://discord.gg/WBdCwAJG), and submit a bug report.

**Comment by MoodyBlueSkies** [comment]
Aww. That's sadge. Thanks for helping, though. Have a nice one bud.
