### ISSUE TITLE
Vetpods are not treated as valid animal beds to rescue to

### ISSUE THREAD

**Issue by techno156** [sumghai/MedPod#79]
**Describe the bug:**  
All variants of the Vetpod are not treated as valid animal beds by the game. This results in the animals not using the Vetpod, and it being impossible to rescue animals to the vetpod. Forcibly relocating the animal to the Vetpod's active spot (in the middle) does not seem to do anything, as the animal will promptly leave and seek out a valid animal bed (if possible).

If a valid animal bed is placed, and the animal goes there/is taken there for rest, it will not move to the vetpod, nor can it be hauled there by pawns.

Tested with pet cat, and pet donkey, against all three sizes of vetpod, on a dev-mode quicktest map. Vetpods are powered by batteries filled using dev mode.

**Expected behavior:**  
It should be possible to rescue the animal to a Vetpod, or have it automatically go to the Vetpod, and be healed of its injuries/diseases.

**Steps to reproduce:**  

1. Spawn animal, and powered Vetpod. 
2. Injure Animal (using dev mode or character creator)
3. Animal cannot be rescued to the Vetpod, with an error stating that there are no valid animal beds.

**Additional information:**

No relevant errors generated on the dev log.

## System and Game Configuration
**Operating System:**  Windows 10 Home 21H1
**Physical RAM:**  16 GB
**RimWorld base game version:**  1.4.3901
**RimWorld DLCs loaded:**  Royalty, Biotech, and Ideology
**MedPod mod version:**  1.5.15
**MedPod mod downloaded from:**  Steam
**Your mod list:**  Harmony 2.2.2, Character Editor 1.4.1242, Medpod 1.5.15

## Declaration

I hereby verify that:
- [X] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Thank you for you bug report.

Are the animals' medical care levels in the Health tab set to Industrial-tech or Best quality medicines?

https://github.com/sumghai/MedPod/wiki/FAQ#q-why-arent-my-pawns-using-medpods
