### ISSUE TITLE
Mod Settings to change what health conditions are cured by MedPod

### ISSUE THREAD

**Issue by techno156** [sumghai/MedPod#80]
**Describe your idea:**

Particularly in modded runs, there might be health conditions added by mods that are not harmful/should not be cured, but the MedPod does anyway, occasionally resulting in glitchy behaviour. 

Ideally, the implementation of this idea would be to have lists of health conditions/types that the MedPod will try to cure, and which ones that it would ignore, inside of the Mod Settings.

**Why do you think your idea would be a good fit for MedPod?:**
Not only would it help resolve some issues with mod collisions, where a mod might add a hediff that causes misbehaviour when the MedPod tries to cure it, but it might also let someone change the difficulty of the MedPod itself. For example, someone who does not wish for the MedPod to cure addictions (such as to Luciferium) could just turn it off in the settings as desired.

**What alternatives/workarounds have you tried?**
Aborting the treatment, and switching off the medpod/restricting the relevant colonist from the medpod if misbehaviour happens. 

## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
Sorry, additional mod settings to allow players to pick and choose which hediffs are treatable are not planned, as per the FAQ:

https://github.com/sumghai/MedPod/wiki/FAQ#q-why-doesnt-the-medpod-allow-players-to-pick-and-choose-which-hediffs-are-allowedprohibited-from-treatment

https://github.com/sumghai/MedPod/wiki/FAQ#q-could-you-add-mod-options
