### ISSUE TITLE
MedPod and Diseases+ compatibility

### ISSUE THREAD

**Issue by Ludi1989** [sumghai/MedPod#82]
Hi there, I've found this part in files related to condition called Genius from _Diseases+_, pawns are stuck in an infinite loop to treat it despite it's been marked as **not being bad**, not **making SickThought** and not **being treatable**:

><HediffDef ParentName="ChronicDiseaseBase">
                <defName>DimonSever000_Genius</defName>
		<label>Genius</label>
		<description>This person has incredible intelligence and a thirst for knowledge, but he is very vulnerable to severe nervous disorders.</description>
		<descriptionHyperlinks>
			<HediffDef>DimonSever000_Schizophrenia</HediffDef>
			<HediffDef>DimonSever000_Inspiration</HediffDef>
			<HediffDef>DimonSever000_Alienation</HediffDef>
		</descriptionHyperlinks>
		<isBad>false</isBad>
		<initialSeverity>1.0</initialSeverity>
		<minSeverity>0.001</minSeverity>
		<maxSeverity>1.0</maxSeverity>
		<tendable>false</tendable>
		<makesSickThought>false</makesSickThought>
		<everCurableByItem>false</everCurableByItem>
		<comps>
			<li Class="Diseases.Hediffs.HediffCompProperties_Storage">
				<comps>
					<li>
						<compClass>Diseases.Hediffs.HediffComp_DiseaseAfterTicks</compClass>
						<intervalTicks>5000000~6000000</intervalTicks>
						<hediffDefs>
							<li>DimonSever000_Schizophrenia</li>
						</hediffDefs>
						<partsToAffect>
							<li>Brain</li>
						</partsToAffect>
						<chance>0.03</chance>
						<letter>true</letter>
					</li>
					<li>
						<compClass>Diseases.Hediffs.HediffComp_DiseaseAfterTicks</compClass>
						<intervalTicks>420000~620000</intervalTicks>
						<hediffDefs>
							<li>DimonSever000_Inspiration</li>
							<li>DimonSever000_Alienation</li>
						</hediffDefs>
						<partsToAffect>
							<li>Brain</li>
						</partsToAffect>
						<chance>0.5</chance>
						<letter>false</letter>
					</li>
				</comps>
			</li>
		</comps>
		<stages>
			<li>
				<partEfficiencyOffset>0.5</partEfficiencyOffset>
				<statOffsets>
					<GlobalLearningFactor>0.5</GlobalLearningFactor>
				</statOffsets>
			</li>
		</stages>
	</HediffDef>
	
</Defs>

**Comment by sumghai** [comment]
Already patched in commit b2d5837, so I'm closing this issue.

Also, please don't deviate from the provided bug reporting template - I use that information to properly diagnose and debug issues.

**Comment by Ludi1989** [comment]
Thanks and sorry at the same time. When I clicked New Issue it clearly stated that **compatibility** should be stated under **bug** section. That is why i put it there

**Comment by Ludi1989** [comment]
Ok, and the template, I will remember about it. Sorry again
