### ISSUE TITLE
No More Riceworld Incompatibility

### ISSUE THREAD

**Issue by RowanSkie** [sumghai/MedPod#83]
**Describe the bug:**  
MedPod is incompatible with [No More Riceworld](https://steamcommunity.com/sharedfiles/filedetails/?id=2990082269&searchtext=no+more+riceworld) by removing the buffs it gives.

**Expected behavior:**  
It doesn't touch the buffs.

**Steps to reproduce:**  

1. Have a well-fed pawn that has full carbohydrates, proteins, and vitamins
2. Pawn uses MedPod
3. Pawn no longer has buffs from having a well-fed diet.

**Additional information:**

## System and Game Configuration
**Operating System:** Windows 11
**Physical RAM:** 64GB
**RimWorld base game version:** 1.4.3901 rev238
**RimWorld DLCs loaded:** All
**MedPod mod version:** 1.5.18
**MedPod mod downloaded from:** Steam
**Your mod list:** [Main Modlist](https://rentry.co/ueqm8kaq) [Testing Modlist](https://rentry.co/hyx4ptxn)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by RowanSkie** [comment]
Edited with a very trimmed modlist to check.

**Comment by sumghai** [comment]
Thanks for the heads-up! 

Looks like the author of No More Riceworld forgot to mark the "full of [nutrient]" hediffs as non-bad, so I'll do it from my end.
