### ISSUE TITLE
Patch for [DN] Bundle Of Traits no longer required in RimWorld 1.5

### ISSUE THREAD

**Issue by Inglix** [sumghai/MedPod#87]
**Describe the bug:**  
An error is thrown on game load while trying to add `BOT_CongenitalAnalgesiaPainReducer` to `neverTreatableHediffs`.

**Expected behavior:**  
No error thrown on game load.

**Steps to reproduce:**  
1. Add both MedPod and [DN] Bundle of Traits to your active mod list
2. Ensure that you are updated to RimWorld 1.5
3. Start the game.

**Additional information:**
The [DN] Bundle of Traits mod no longer uses a hediff named `BOT_CongenitalAnalgesiaPainReducer` when used in RimWorld 1.5, so the patch in `Patches_BundleOfTraits.xml` is only needed for 1.4 and lower. 

The error message displayed in the log is 
`Could not resolve cross-reference to Verse.HediffDef named BOT_CongenitalAnalgesiaPainReducer (wanter=neverTreatableHediffs)`

Link to full log: https://gist.github.com/HugsLibRecordKeeper/7efe397e9205d4f265ea37c7098891ef

## System and Game Configuration
**Operating System:** Windows 11 Pro
**Physical RAM:** 64.0 GB
**RimWorld base game version:** 1.5.4069
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech, Anomaly
**MedPod mod version:** 1.5.22
**MedPod mod downloaded from:** Steam
**Your mod list:** Harmony 2.3.1.0, HugsLib 11.0.3, MedPod 1.5.22, [DN] Bundle Of Traits 3.0.0

## Declaration

I hereby verify that:
- [x ] I am running the latest version of the game, MedPod and its dependencies
- [x ] I am NOT running any mods with known incompatibilities with MedPod
- [x ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x ] I have confirmed that the issue does not happen if MedPod is disabled
- [x ] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x ] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Thanks for the heads-up, @Inglix - I'll have this rolled into the next update.
