### ISSUE TITLE
Unable to interact with dead pawns

### ISSUE THREAD

**Issue by PaddySackers** [sumghai/MedPod#89]
**Describe the bug:**  
When I try and right click a dead pawn nothing happens, this only happens if I have a Medpod in my colony, if I dismantle the Medpod it works as normal

**Expected behavior:**  
A float menu to appear with, strip, haul etc.

**Steps to reproduce:**  

1. Construct a med pod
2. Kill any pawn
3. Right click to strip or interact

**Additional information:**

 Root level exception in OnGUI(): System.InvalidCastException: Specified cast is not valid.
[Ref E25F84A7]
 at MedPod.Harmony_FloatMenuMakerMap_OverrideRescueWithMedPodVersion.Postfix (UnityEngine.Vector3 clickPos, Verse.Pawn pawn, System.Collections.Generic.List`1[Verse.FloatMenuOption]& opts) [0x003e4] in <a1812a2ee64f4630b870054c2af28035>:0 
 at RimWorld.FloatMenuMakerMap.AddHumanlikeOrders (UnityEngine.Vector3 clickPos, Verse.Pawn pawn, System.Collections.Generic.List`1[T] opts) [0x07158] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - TRANSPILER vanillaexpanded.factions.deserters: IEnumerable`1 VFED.HarmonyPatches.MiscPatches:CheckBiosecurity(IEnumerable`1 instructions, ILGenerator generator)
     - TRANSPILER SmashPhil.VehicleFramework: IEnumerable`1 Vehicles.CaravanFormation:AddHumanlikeOrdersLoadVehiclesTranspiler(IEnumerable`1 instructions, ILGenerator ilg)
     - TRANSPILER PerformanceOptimizer.Main: IEnumerable`1 PerformanceOptimizer.Optimization_FasterGetCompReplacement:Transpiler(IEnumerable`1 instructions, MethodBase method)
     - PREFIX OskarPotocki.VFECore: Void VanillaWeaponsExpanded.FloatMenuMakerMap_AddHumanlikeOrders_Patch:Prefix(Pawn pawn)
     - PREFIX Harmony_PrisonLabor: Void PrisonLabor.HarmonyPatches.Triggers+AddHumanlikeOrders:Prefix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX GeologicalLandformsMod.Main: Void GeologicalLandforms.Patches.Patch_RimWorld_FloatMenuMakerMap:AddHumanlikeOrders(Vector3& clickPos, Pawn& pawn, List`1& opts)
     - POSTFIX RedMattis.BetterPrerequisites: Void BigAndSmall.FloatMenuMakerMap_AddHumanlikeOrders_Patch:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX Neronix17.TabulaRasa.RimWorld: Void TabulaRasa.Patch_FloatMenuMakerMap_AddHumanlikeOrders:PostFix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX OskarPotocki.VFECore: Void VanillaWeaponsExpanded.FloatMenuMakerMap_AddHumanlikeOrders_Patch:Postfix()
     - POSTFIX OskarPotocki.VFECore: Void VFECore.Patch_FloatMenuMakerMap+AddHumanlikeOrders_Fix:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX VFEEmpire.Mod: Void VFEEmpire.HarmonyPatches.Patch_AddHumanlikeOrders:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX VanillaExpanded.VFEA: Void VFEAncients.HarmonyPatches.BuildingPatches:AddCarryJobs(List`1 opts, Vector3 clickPos, Pawn pawn)
     - POSTFIX PeteTimesSix.SimpleSidearms: Void PeteTimesSix.SimpleSidearms.Intercepts.FloatMenuMakerMap_AddHumanLikeOrders_Postfix:AddHumanlikeOrders(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX alt4s.visitsettlements: Void VS_SettlementInteractionMenu:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX BrainwashMod: Void Brainwash.FloatMenuMakerMap_AddHumanlikeOrders_Patch:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX com.MedPod.patches: Void MedPod.Harmony_FloatMenuMakerMap_OverrideRescueWithMedPodVersion:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX legodude17.mvcf: Void MVCF.PatchSets.PatchSet_Brawlers:AddHumanlikeOrders_Postfix(List`1 opts, Vector3 clickPos, Pawn pawn)
     - POSTFIX legodude17.mvcf: Void MVCF.Utilities.FloatMenuUtility:AddWeaponReloadOrders(List`1 opts, Vector3 clickPos, Pawn pawn)
     - POSTFIX jecstools.jecrell.humanlikeorders: Void JecsTools._HumanlikeOrdersUtility:AddHumanlikeOrders_PostFix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX OskarPotocki.HeavyWeapons: Void HeavyWeapons.Patch_FloatMenuMakerMap+AddHumanlikeOrders_Fix:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX OskarPotocki.VanillaPsycastsExpanded: Void VanillaPsycastsExpanded.Technomancer.Psyring:EquipConditions(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX Harmony_PrisonLabor: Void PrisonLabor.HarmonyPatches.Patches_TakeToBed.Patch_AddTakeToBed:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX Harmony_PrisonLabor: Void PrisonLabor.HarmonyPatches.Patches_GUI.GUI_RMB.Patch_RMB_Chains:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX rimworld.rimquest: Void RimQuest.HarmonyPatches:AddHumanlikeOrders(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX com.alphamemes: Void AlphaMemes.AlphaMemes_FloatMenuMakerMap_AddHumanlikeOrders_Patch:AddDragRelicToAltar(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX CP.Casevac: Void Casevac.FloatMenuMakerCarryAdder:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX CP.FirstAid: Void FirstAid.FloatMenuMakerCarryAdder:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX ChickenPlucker.CapturedPersonsPatches: Void CapturedPersons.AddHumanlikeOrdersPatch:Postfix(Vector3 clickPos, Pawn pawn, List`1& opts)
     - POSTFIX Linkolas.Stabilize: Void Stabilize.Patches+FloatMenuMakerCarryAdder:AddHumanlikeOrdersPostfix(Vector3 clickPos, Pawn pawn, List`1 opts)
     - POSTFIX com.calltradeships.rimworld.mod: Void CallTradeShips.Patch_FloatMenuMakerMap_AddHumanlikeOrders:Postfix(Vector3 clickPos, Pawn pawn, List`1 opts)
 at RimWorld.FloatMenuMakerMap.ChoicesAtFor (UnityEngine.Vector3 clickPos, Verse.Pawn pawn, System.Boolean suppressAutoTakeableGoto) [0x000d1] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - POSTFIX OskarPotocki.VFECore: Void VFE.Mechanoids.HarmonyPatches.FloatMenuMakerMap_ChoicesAtFor_Patch:Postfix(List`1& __result, Vector3 clickPos, Pawn pawn, Boolean suppressAutoTakeableGoto)
     - POSTFIX Neronix17.Asimov.RimWorld: Void Asimov.Patch_FloatMenuMakerMap_ChoicesAtFor:Postfix(List`1& __result, Vector3 clickPos, Pawn pawn, Boolean suppressAutoTakeableGoto)
     - POSTFIX net.pardeike.rimworld.mods.achtung: Void AchtungMod.FloatMenuMakerMap_ChoicesAtFor_Postfix:Postfix(List`1 __result, Vector3 clickPos, Pawn pawn)
     - POSTFIX DraftableAnimals.Mod: Void DraftableAnimals.FloatMenuMakerMap_ChoicesAtFor_Patch:Postfix(List`1& __result, Vector3 clickPos, Pawn pawn, Boolean suppressAutoTakeableGoto)
 at AchtungMod.MultiActions.AddColonist (AchtungMod.Colonist colonist) [0x0001f] in <c48846fe21134b1d9cad8f1931a7d35c>:0 
 at AchtungMod.Tools.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <c48846fe21134b1d9cad8f1931a7d35c>:0 
 at <0x1e867f46b50 + 0x002ca> <unknown method>
 at AchtungMod.Controller.MouseDown (UnityEngine.Vector3 pos, System.Int32 button, System.Boolean longPress) [0x00090] in <c48846fe21134b1d9cad8f1931a7d35c>:0 
 at AchtungMod.Controller.HandleEvents () [0x000cf] in <c48846fe21134b1d9cad8f1931a7d35c>:0 
 at AchtungMod.Selector_HandleMapClicks_Patch.Prefix () [0x00005] in <c48846fe21134b1d9cad8f1931a7d35c>:0 
 at RimWorld.Selector.HandleMapClicks () [0x0000e] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - PREFIX net.pardeike.rimworld.mods.achtung: Boolean AchtungMod.Selector_HandleMapClicks_Patch:Prefix()
     - PREFIX SmashPhil.VehicleFramework: Boolean Vehicles.Extra:MultiSelectFloatMenu(List`1 ___selected)
     - PREFIX net.littlewhitemouse.LWM.DeepStorage: Boolean LWM.DeepStorage.Patch_HandleMapClicks:Prefix(Selector __instance, List`1 ___selected)
 at RimWorld.Selector.SelectorOnGUI () [0x00000] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
 at RimWorld.MapInterface.HandleLowPriorityInput () [0x0000f] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
 at RimWorld.UIRoot_Play.UIRootOnGUI () [0x000eb] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - PREFIX SmashPhil.SmashTools: Void SmashTools.MainMenuKeyBindHandler:HandleKeyInputs()
     - POSTFIX Krkr.RocketMan: Void RocketMan.KeyBinder:OnGUI()
 at Verse.Root.OnGUI () [0x00046] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - POSTFIX UnlimitedHugs.HugsLib: Void HugsLib.Patches.Root_OnGUI_Patch:OnGUIHookUnfiltered()
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch3 (string)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root.OnGUI_Patch1 (Verse.Root)

## System and Game Configuration
**Operating System:** 
**Physical RAM:** 
**RimWorld base game version:** 
**RimWorld DLCs loaded:** 
**MedPod mod version:** 
**MedPod mod downloaded from:** 
**Your mod list:** 
I hereby verify that:
- [ ] I am running the latest version of the game, MedPod and its dependencies
- [ ] I am NOT running any mods with known incompatibilities with MedPod
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [ ] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
You are running over 400 mods.

Per the bug reporting guidelines, please strip your modlist down to the bare minimum (<5) mods needed to reproduce this issue, then update this bug report.

**Comment by sumghai** [comment]
Closing this issue, as the original report has not been amended to the required bug reporting format with the missing information.

@PaddySackers, please read the [troubleshooting guide](https://gist.github.com/sumghai/71da62f9f4a3c8f377acd1fd9655e6de), narrow down your mod list to only the bare minimum (<5 mods) required to reproduce the issue, then submit a new bug report by precisely following the provided template with all necessary information.
