### ISSUE TITLE
diagnostis loop

### ISSUE THREAD

**Issue by Maxer4000** [sumghai/MedPod#91]
**Describe the bug:**  

some pawn would be stuck inside the medpod and keep being diagnosed on loop, even when aborted the pawn would just become immobile prompting doctors to put them back in to continue the loop
**Expected behavior:**  

**Steps to reproduce:**  

1. Have a pawn that has any immobile condition to use the medpod
2. Doctor put said pawn in medpod
3. Loop start

**Additional information:**

## System and Game Configuration
**Operating System:*Microsoft Windows 10 (64-bit)* 
**Physical RAM:*16.0 GB* 
**RimWorld base game version:*1.5.4104* 
**RimWorld DLCs loaded:*Ideology, Royalty, Biotech, Abnomaly* 
**MedPod mod version:** 
**MedPod mod downloaded from:*Steam* 
**Your mod list:** 

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [X] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Bug confirmed - thank you for your bug report.

Looks like one of the health state checks in the `DischargePatient()` method was checking (and somehow maintaining) the downed state of a patient, instead of querying `ShouldBeDowned()`.

Should be a quick fix.

**Comment by hamiltonj-troubleshooting** [comment]
Till the last update I had been using this on 1.4 (waiting on mods, didnt notice the issue till hour or so ago when I restarted RW. ) Seems to be the same issue that was corrected in 1.5, patient lays down, can see on the medpod diagnosis going from 0-100% then no further progress.

**Comment by sumghai** [comment]
> Till the last update I had been using this on 1.4 (waiting on mods, didnt notice the issue till hour or so ago when I restarted RW. ) Seems to be the same issue that was corrected in 1.5, patient lays down, can see on the medpod diagnosis going from 0-100% then no further progress.

Please check the v1.5.28 update and see if that fixes your issue.

**Comment by hamiltonj-troubleshooting** [comment]
Yeah I seen the update for 1.5.28. Confirmed I have that as my current version in the mod list. Looked at the 1.5/1.4 folders in the mod folder and seen the dll for 1.4 being modified a while ago and 1.5 is recent so I was kinda thinking the recent changes shouldn't impacted my setup due to still being on 1.4. Not a modder so I don't know the complete details if that statement is correct. or not.  Not seeing the new gizmo button related to guests either but being on 1.4 still wasn't expecting too really. Up till today had no prior issues with the mod on 1.4.

**Comment by hamiltonj-troubleshooting** [comment]
Grabed a copy just now of the 1.5.26 and swapped that into the mod folder and reloaded, confirmed the issue went away. Again I'm on 1.4 still so doesnt really matter I guess.

**Comment by sumghai** [comment]
> Yeah I seen the update for 1.5.28. Confirmed I have that as my current version in the mod list. Looked at the 1.5/1.4 folders in the mod folder and seen the dll for 1.4 being modified a while ago and 1.5 is recent so I was kinda thinking the recent changes shouldn't impacted my setup due to still being on 1.4. Not a modder so I don't know the complete details if that statement is correct. or not. Not seeing the new gizmo button related to guests either but being on 1.4 still wasn't expecting too really. Up till today had no prior issues with the mod on 1.4.

> Grabed a copy just now of the 1.5.26 and swapped that into the mod folder and reloaded, confirmed the issue went away. Again I'm on 1.4 still so doesnt really matter I guess.

As a general rule, I don't backport code changes from the latest game version (RW 1.5) to any earlier versions (1.4), or actively provide support for earlier versions. They are only included to help players quickly migrate to RW 1.5. So if you remain on RW 1.4, you will never see any bugfixes I implemented from RW 1.5 onwards.
