### ISSUE TITLE
MedPod does not treat pawns in 1.4

### ISSUE THREAD

**Issue by DXwer** [sumghai/MedPod#92]
**Describe the bug:**  

When a pawn gets in the MedPod, they will be diagnosed. After that, the MedPod will display "Diagnosis Complete" without doing anything else. The pawn must be ejected from the MedPod. Additionally, the Guest gizmo does not appear.

**Expected behavior:**  

A pawn should get in the MedPod, be diagnosed, and be treated. There should be a gizmo to allow/disallow guest usage.

**Steps to reproduce:**  

1. Build a MedPod
2. Wait for a pawn to be injured
3. Let the pawn use the MedPod

**Additional information:**

At load: 
Failed to find Verse.HediffDef named MedPod_InducedComa. There are 118 defs of this type loaded.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DefDatabase`1<Verse.HediffDef>:GetNamed (string,bool)
Verse.GenDefDatabase:GetDef (System.Type,string,bool)
RimWorld.DefOfHelper:BindDefsFor (System.Type)
System.Threading.Tasks.Parallel/<>c__DisplayClass31_0`2<System.Type, object>:<ForEachWorker>b__0 (int)
System.Threading.Tasks.Parallel/<>c__DisplayClass17_0`1<object>:<ForWorker>b__1 ()
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:InnerInvokeWithArg (System.Threading.Tasks.Task)
System.Threading.Tasks.Task/<>c__DisplayClass178_0:<ExecuteSelfReplicating>b__0 (object)
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

Upon completing diagnosis: 
Exception ticking MedPodStandard3611 (at (79, 0, 69)): System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.HediffMaker.MakeHediff (Verse.HediffDef def, Verse.Pawn pawn, Verse.BodyPartRecord partRecord) [0x0001a] in <cd7169108ea74757aa50c5b33d275c15>:0 
  at MedPod.Building_BedMedPod.AnesthesizePatient (Verse.Pawn patientPawn) [0x00000] in <989977aefb8b48afb0419f685d0e9939>:0 
  at MedPod.Building_BedMedPod.DiagnosePatient (Verse.Pawn patientPawn) [0x00115] in <989977aefb8b48afb0419f685d0e9939>:0 
  at MedPod.Building_BedMedPod.Tick () [0x00172] in <989977aefb8b48afb0419f685d0e9939>:0 
  at Verse.TickList.Tick () [0x0015c] in <cd7169108ea74757aa50c5b33d275c15>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.TickList:Tick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

## System and Game Configuration
**Operating System:**  Windows 11 (64 bit)
**Physical RAM:**  32 GB
**RimWorld base game version:**  1.4.3901
**RimWorld DLCs loaded:**  None
**MedPod mod version:**  1.5.28
**MedPod mod downloaded from:**  Steam
**Your mod list:**  Harmony 2.3.1.0

## Declaration

I hereby verify that:
- [ ] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Thank you for your report, but unfortunately any bugfixes or feature enhancement I make are solely for the latest (RW 1.5) version of the game. The RW 1.4 DLL was only included to help players migrate their existing savegame to RW 1.5 at the earliest opportunity.

Please update your game as soon as possible.
