### ISSUE TITLE
Staged HeDiffs: Change treatment based on stage

### ISSUE THREAD

**Issue by chill0r** [sumghai/MedPod#93]
**Describe your idea:**
Currently any HeDiffs with ```<isBad>true</isBad>``` are treated.
For HeDiffs with multiple stages this means that the Pawn will use the MedPod on all stages.
Depending on the HeDiff some stages aren't bad so they (should) not be treated.

Because of this it'd be nice to have a option to define which stage should be treated (or which is the first one to be bad)

## Declaration

I hereby verify that:
- [X] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [X] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
I've individually reviewed nearly every hediff with `<isBad>true</isBad>`, and so far all of them warrant treatment by MedPods irrespective of severity/stage.

Which specific hediffs do you think should be state-dependent?

**Comment by sumghai** [comment]
Closing this feature request due to inactivity and lack of clarification.

@chill0r - if you wish to reopen this discussion, please provide specific use cases of hediffs that should be selectively treated based on stage (e.g. "hediff XYZ should not be treated at stage 123 or below").
