### ISSUE TITLE
Save Our Ship 2: MedPods lose medical bed status when ship is moved

### ISSUE THREAD

**Issue by Gryby64** [sumghai/MedPod#96]
Problem:
Save our Ship 2, after moving ship all medpods turn green so they no longer can be used

Workaround:
Reinstalling the building (rotating in place)

Suggested solution:
If save our ship 2 is installed show "Medical" gizmo

RimWorld DLCs loaded: all
MedPod mod version: 1.5.33
MedPod mod downloaded from: steam
Your mod list: harmony, core, dlc, hugslib, medpod, vehicles framework, SOS 2.7

I hereby verify that:
- [X] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [X] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [X] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Hmm, this does sound rather peculiar.

I disabled the Medical gizmo from MedPod beds, because MedPods are always meant to be for medical use only, and I wanted to prevent players from accidentally turning them into regular beds. 

Re-enabling the gizmo just to provide players a way to work around this specific SOS2 bug isn't ideal, as it re-introduces the aforementioned problem. A more robust approach would be to understand why moving a ship that contains a MedPod resets the bed type/state, and to figure out a way to compensate for that under the hood without requiring player intervention.

@KentHaeger - any particular reason why SOS2 may cause a bed to change its type/state from medical to non-medical?

**Comment by FGRemastered** [comment]
I think SOS2 re-generates the map when you move the ship, causing all buildings to be unclaimed for a moment and any unclaimed bed defaults to general use.

**Comment by sumghai** [comment]
> I think SOS2 re-generates the map when you move the ship, causing all buildings to be unclaimed for a moment and any unclaimed bed defaults to general use.

I had an inkling this was the case, but I'm trying to confirm with the current developers/maintainers of SOS2.

**Comment by sumghai** [comment]
Still haven't heard back from @KentHaeger or Thain (via Discord), so there's not much I can do until then. Will keep this issue open in the meantime.

**Comment by sumghai** [comment]
According to Thain (via Discord):
> It's kindof an ongoing issue between SOS2 and other mods. A solution evades us so far, as some mods just struggle to transfer settings between buildings, including container mod display states (the stuff transfers and the stack size transfers, but not the display which reads as default stack size until the game is reloaded. Stuff like that.)

As for whether this was something that should be fixed on MedPod's side, or on SOS2's side:
> I'll get back to you. There's a solution but I'll have to dig it out. Was added right before the SonicTHI fiasco, which was so stressful it just wiped all memory from my brain.

So I'll leave this issue open for now, pending an update from Thain and the rest of the SOS2 dev team.

**Comment by sumghai** [comment]
@KentHaeger suggested adding the `SoSSpawnOverride` ModDefExtension to the MedPod def, which would tell SOS2 to treat respawned MedPods as a brand-new building. However, I'm unsure what other unforeseen effects this may have on MedPod spawning behavior.

@FGRemastered - One thing I've noticed is that vanilla hospital beds retain their medical bed settings, despite sharing similar medical bed default settings with MedPods.

In the end, I ended up with a C# code kludge that hardcodes the MedPod bed to always be set to medical on spawn/respawn. In my own dev save, moving the ship no longer adversely affects the medical bed status of MedPods.

@Gryby64 - Please try the following dev build, and verify that it fixes your issue:

https://github.com/sumghai/MedPod/archive/779539e9e582e1511d0ea871bbfaf762ca2b687c.zip

**Comment by sumghai** [comment]
As there has been no further response or feedback from @Gryby64, I can only assume that the fix works, so I'll mark this one as done.
