### ISSUE TITLE
Assembly-CSharp_public.dll

### ISSUE THREAD

**Issue by tamiaolegemide** [sumghai/MedPod#99]
Hi sir,Your mod  is really exciting。I want change some parameter ,but i don't know Assembly-CSharp_public.dll where it is ,Where can I find it?
I only find Assembly-CSharp.dll.

**Describe the bug:**  

**Expected behavior:**  

**Steps to reproduce:**  

1.
2.
3.

**Additional information:**

## System and Game Configuration
**Operating System:** 
**Physical RAM:** 
**RimWorld base game version:** 
**RimWorld DLCs loaded:** 
**MedPod mod version:** 
**MedPod mod downloaded from:** 
**Your mod list:** 

## Declaration

I hereby verify that:
- [ ] I am running the latest version of the game, MedPod and its dependencies
- [ ] I am NOT running any mods with known incompatibilities with MedPod
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [ ] I have confirmed that the issue does not happen if MedPod is disabled
- [ ] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [ ] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
`Assembly-CSharp_public.dll` is a publicized version of RimWorld's regular `Assembly-CSharp.dll` assembly, which make all private fields and methods public for ease of mod development.

You'll need to find a suitable tool for publicizing assemblies on your own.

Also, this is not a bug report.

**Comment by tamiaolegemide** [comment]
I'm sorry to disturb you,.
Thank you for your explain,i appreciate it indeed!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
